development:
  adapter: mysql2
  encoding: utf8
  database: crud_dev
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: crud_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: crud_production
  pool: 5
  username: root
  password:
